services:


######################################################################
#************************** 🧬 PROXY / NGINX *************************
######################################################################


  modsecurity:
    container_name: modsecurity 
    build:
      context: .
      dockerfile: ./services/security/temp/Dockerfile
      args:
        HOME: ${HOME}
        NODE_ENV: ${NODE_ENV}

    ports:
      - 443:443
    networks:
      - internal
    expose:
      - 443
    env_file:
      - .env
    depends_on:
      - gateway


  gateway:
    container_name: gateway
    build:
      context: .
      args: {}
      dockerfile: ./services/gateway/Dockerfile
    networks:
    - transcendence
    - internal
    expose:
      - 8080:80
    volumes:
      - ./services/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    user: "0:0"
    restart: unless-stopped
    environment: {}
    depends_on:
      - auth_app
      - live-chat_app


######################################################################
#************************** 📦 BACKEND *******************************
######################################################################

# AUTH_SERVICE : 3000
# LANGUAGE_MANAGER_SERVICE : 3001
# LIVE_CHAT_SERVICE : 3002
# REMOTE_PLAYER_SERVICE : 3003
# MATCH_MAKING : 3004
# SERVER-RENDERING : 3003

  server-rendering_app:
    container_name: server-rendering_app
    build:
      context: ./services
      dockerfile: server-rendering/app/Dockerfile
    expose:
      - 3005
    volumes:
      - /data/node_modules
      # - ./services/server-rendering/app:/data
      # - sqlite_data:/data
      # - ./volume/redis_data:/data
    networks:
      - internal
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - NODE_ENV=${NODE_ENV}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  auth_app:
    container_name: auth_app
    build:
      context: ./services/auth/app
    expose:
      - 3000:3000
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - FORTYTWO_CLIENT_ID=${FORTYTWO_CLIENT_ID}
      - FORTYTWO_CLIENT_SECRET=${FORTYTWO_CLIENT_SECRET}
      - FORTYTWO_REDIRECT_URI=${FORTYTWO_REDIRECT_URI}
    volumes:
      - /data/node_modules
      # - sqlite_data:/data/sqlite
      # - ./volume/redis_data:/data
      - ./services/auth/app:/data
    networks:
      - internal
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure

  language-manager:
    container_name: language-manager_app
    build:
      context: ./services/language-manager
    expose:
      - 3001
    volumes:
      - ./services/language-manager:/data
      - /data/node_modules
    networks:
      - internal

  live-chat_app:
    container_name: live-chat_app
    build:
      context: ./services/live-chat/app
    expose:
      - 3002
    volumes:
      - ./services/live-chat/app:/data
      - /data/node_modules
    networks:
      - internal

  remote-players_app:
    container_name: remote-players_app
    build:
      context: ./services/remote-players/app
    expose:
      - 3003
    networks:
      - internal

  match-maker_app:
    container_name: match-maker_app
    build:
      context: ./services/match-maker/app
    expose:
      - 3004
    # volumes:
    #   - sqlite_data:/data
    networks:
      - internal


######################################################################
#*************************🚀 CORE SERVICES ***************************
######################################################################


  mailpit:
    image: axllent/mailpit
    container_name: gt_mailpit
    ports:
      - "8025:8025"    # Interface web
      - "1025:1025"    # SMTP
    restart: unless-stopped
    networks:
      - internal

  mail:
    container_name: mail
    build:
      context: ./services/mail/app/
    ports:
      - 3300:3300
    environment:
      - NODE_ENV=${NODE_ENV}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASSWORD=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - ./services/mail/app:/data
      - /data/node_modules
    networks:
      - internal
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    restart: on-failure


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - "5672:5672"    # port principal AMQP (clients)
      - "15672:15672"  # interface web management
    environment:
      - NODE_ENV=${NODE_ENV}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s 
    networks:
      - internal
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"    
    networks:
      - internal
    volumes:
      - ./volumes/redis_data:/data

######################################################################
#************************** 📦 FRONTEND *******************************
######################################################################

  frontend_app:
    container_name: frontend_app
    build:
      context: ./services/frontend
    expose:
      - 3006
    volumes:
      - ./services/frontend/srcs:/app/srcs
      - ./services/frontend/locales:/app/locales
    networks:
      - internal
      - transcendence


######################################################################
######################### 🌐​ NETWORKS & VOLUMES ######################
######################################################################

networks:
  internal:
    driver: bridge
  transcendence:
    driver: bridge
