services:


######################################################################
#************************** 🧬 PROXY / NGINX *************************
######################################################################

  gateway:
    container_name: gateway
    build:
      context: .
      args: {}
      dockerfile: ./requirements/gateway/Dockerfile
    networks:
    - transcendence
    - internal
    ports:
      - "8080:80"
    volumes:
      - ./requirements/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
    user: "0:0"
    restart: unless-stopped
    environment: {}
    depends_on:
      - auth_app
      - live-chat_app


######################################################################
#************************** 📦 BACKEND *******************************
######################################################################

# AUTH_SERVICE : 3000
# LANGUAGE_MANAGER_SERVICE : 3001
# LIVE_CHAT_SERVICE : 3002
# REMOTE_PLAYER_SERVICE : 3003


  auth_app:
    container_name: auth_app
    build:
      context: ./requirements/auth/app
    expose:
      - 3000
    volumes:
      - ./volumes/auth:/data
    networks:
      - internal

  language-manager_app:
    container_name: language-manager_app
    build:
      context: ./requirements/language-manager/app
    expose:
      - 3001
    # volumes:
    #   - sqlite_data:/data
    networks:
      - internal

  live-chat_app:
    container_name: live-chat_app
    build:
      context: ./requirements/live-chat/app
    expose:
      - 3002
    volumes:
      - ./volumes/live-chat:/data
    networks:
      - internal

  remote-players_app:
    container_name: remote-players_app
    build:
      context: ./requirements/remote-players/app
    expose:
      - 3003
    networks:
      - internal

  match-maker_app:
    container_name: match-maker_app
    build:
      context: ./requirements/match-maker/app
    expose:
      - 3004
    # volumes:
    #   - sqlite_data:/data
    networks:
      - internal


######################################################################
#*************************🚀 CORE SERVICES ***************************
######################################################################



######################################################################
######################### 🌐​ NETWORKS & VOLUMES ######################
######################################################################

networks:
  internal:
    driver: bridge
  transcendence:
    driver: bridge
