services:

  gateway:
    container_name: gateway
    build:
      context: .
      args: {}
      dockerfile: ./requirements/gateway/Dockerfile
    networks:
    - transcendence
    - internal
    volumes:
      - ./requirements/gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    environment: {}
    depends_on: {}

  auth_app:
    container_name: auth_app
    build:
      context: ./requirements/auth/app
    expose:
      - 3000
    networks:
      - internal

  auth_nginx:
    container_name: auth_nginx
    build:
      context: ./requirements/auth
    depends_on:
      - auth_app
    ports:
      - "8080:80"
    networks:
      - internal
      - transcendence

networks:
  internal:
    driver: bridge
  transcendence:
    driver: bridge

