# Redirection HTTP → HTTPS
server {
    listen 80;
    server_name localhost;

    return 301 https://$host$request_uri;
}

# HTTPS avec reverse proxy
server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    location / {
        proxy_pass http://gateway:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}