# Generated by Django 5.2.2 on 2025-06-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcendanceuser',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
