export interface Translations {
    signinTitle: string;
    login: string;
    passwd: string;
    signin: string;
    forgotPasswd: string;
    guestTitle: string;
    nickname: string;
    chooseAvatar: string;
    play: string;
    back: string;
    signupTitle: string;
    signup: string;
    signupBtn: string;
    email: string;
    otherUp: string;
    passwdConfirm: string;
    resetPasswd: string;
    options: string;
    optionsMessage: string;
    lang: string;
    language: string;
    playAsGuest: string;
    about: string;
    title: string;
    other: string;
    errLength: string;
    errUpper: string;
    errLower: string;
    errNbr: string;
    errMatch: string;
    errEmail: string;
}
//# sourceMappingURL=types.d.ts.map